org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT
oraculum_version=0.0.2-1.21.1
oraculum_version_range=[0.0.1-1.21.1,)
jei_version=19.27.0.340
jei_version_range=[19.27.0.340,)
crafttweaker_version=21.0.38
crafttweaker_version_range=[21.0.38,)
architectury_version=13.0.8
rhino_version=2101.2.7-build.88
kubejs_version=2101.7.2-build.369
kubejs_version_range=[2101.7.2-build.368,)
mod_id=oraculumworktables
mod_name=OraculumWorktables
mod_license=Apache 2.0
mod_version=1.0.0
mod_group_id=com.lirxowo
mod_authors=LirxOwO
mod_description=None.
